Repository lxodud/TimePaper, pull requests merged in 2025-03, with the labels that each got.

#51 [SSD-108] 타임페이퍼 조회 api 연동
  frontend/src/api/api.js
  frontend/src/pages/timepaperDetail/TimePaperDetail.jsx
  frontend/src/pages/timepaperDetail/timepaperdetail.module.css
Labels: feat

#50 [SSD-110] 로그아웃 api 구현
  backend/src/main/java/com/timepaper/backend/global/auth/controller/AuthController.java
  backend/src/main/java/com/timepaper/backend/global/auth/service/AuthService.java
  backend/src/main/java/com/timepaper/backend/global/auth/token/service/RefreshTokenService.java
  backend/src/main/java/com/timepaper/backend/global/auth/token/util/RefreshTokenUtil.java
Labels: feat

#53 [SSD-113]사용자 정보 상태 관리 수정
  frontend/src/App.jsx
  frontend/src/store/slices/authSlice.js
Labels: fix

#49 [SSD-103] 타임페이퍼 잠금 페이지 API 연동
  backend/src/main/java/com/timepaper/backend/domain/timepaper/controller/TimePaperController.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/entity/TimePaper.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/service/TimePaperService.java
  backend/src/main/java/com/timepaper/backend/global/config/WebConfig.java
  backend/src/main/resources/application.properties
  frontend/src/api/api.js
  frontend/src/api/apiInstance.js
  frontend/src/pages/timepapersetlocked/TimePaperSetLock.jsx
  frontend/src/router/index.jsx
Labels: feat

#38 [SSD-86] 타임페이퍼 생성 페이지 api 연동
  backend/src/main/java/com/timepaper/backend/domain/my/dto/response/MyTimepaperListResponseDto.java
  frontend/src/pages/login/Login.jsx
  frontend/src/pages/timepapercreate/TimePaperCreate.jsx
Labels: feat

#57 [SSD-112] 타임페이퍼 삭제 api 연동
  backend/src/main/java/com/timepaper/backend/domain/postit/repository/PostitRepository.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/controller/TimePaperController.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/service/TimePaperService.java
  frontend/src/api/api.js
  frontend/src/components/confirmmodal/ConfirmModal.jsx
  frontend/src/components/confirmmodal/ConfirmModal.module.css
  frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
  frontend/src/pages/time-paper-detail/TimePaperDetail.module.css
Labels: feat

#42 [SSD-69] 회원가입 api 구현
  backend/build.gradle
  backend/src/main/java/com/timepaper/backend/domain/user/entity/User.java
  backend/src/main/java/com/timepaper/backend/global/auth/controller/AuthController.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/CertificationNumberRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/EmailCertificationRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/SignupDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/repository/AuthRepository.java
  backend/src/main/java/com/timepaper/backend/global/auth/service/AuthService.java
  backend/src/main/java/com/timepaper/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/timepaper/backend/global/config/WebConfig.java
  backend/src/main/java/com/timepaper/backend/global/emailsender/EmailSendManager.java
  backend/src/main/resources/application.properties
Labels: feat

#60 [SSD-125] 타임페이퍼 잠금 페이지 이동시 404에러 처리
  frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
Labels: fix

#62 [SSD-123] 타임페이퍼 생성 예외 처리
  frontend/src/pages/time-paper-create/TimePaperCreate.jsx
Labels: fix, refactor

#11 [SSD-63] 회원가입 UI 페이지 구현
  frontend/src/api/api.js
  frontend/src/api/apiInstance.js
  frontend/src/components/BottomButton/BottomButton.jsx
  frontend/src/pages/ModalTest.jsx
  frontend/src/pages/SignUp.jsx
  frontend/src/pages/login/Login.jsx
  frontend/src/pages/login/Login.module.css
  frontend/src/pages/signup/SignUp.jsx
  frontend/src/pages/signup/SignUp.module.css
  frontend/src/router/index.jsx
  frontend/vite.config.js
  frontend/yarn.lock
Labels: feat

#81 [SSD-128] 포스트잇 삭제 api 연동
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/api.js
  frontend/src/components/BottomButton/BottomButton.module.css
  frontend/src/components/Modal/Modal.jsx
  frontend/src/components/Modal/Modal.module.css
  frontend/src/components/PostItDetail.jsx
  frontend/src/components/confirmmodal/ConfirmModal.module.css
  frontend/src/components/dropdownmenu/Dropdown.jsx
  frontend/src/components/dropdownmenu/Dropdown.module.css
  frontend/src/pages/ModalTest.jsx
  frontend/src/pages/postit-create/PostItCreate.jsx
  frontend/src/pages/time-paper-detail/TimePaperDetail.jsx
  frontend/src/pages/time-paper-detail/TimePaperDetail.module.css
  frontend/yarn.lock
Labels: feat

#86 [SSD-147] refactor: 요청 DTO validation 및 응답 공통화
  backend/src/main/java/com/timepaper/backend/domain/postit/dto/PostitCreateRequestDto.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/controller/TimePaperController.java
  backend/src/main/java/com/timepaper/backend/domain/timepaper/dto/request/TimePaperLockRequestDto.java
  backend/src/main/java/com/timepaper/backend/domain/user/dto/request/LoginRequestDto.java
  backend/src/main/java/com/timepaper/backend/domain/user/dto/request/SignUpRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/controller/AuthController.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/CertificationNumberRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/EmailCertificationRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/dto/SignupRequestDto.java
  backend/src/main/java/com/timepaper/backend/global/auth/filter/LoginFilter.java
  backend/src/main/java/com/timepaper/backend/global/auth/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/timepaper/backend/global/auth/handler/CustomAuthenticationFailureHandler.java
  backend/src/main/java/com/timepaper/backend/global/auth/service/AuthService.java
  backend/src/main/java/com/timepaper/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/timepaper/backend/global/exception/handler/GlobalExceptionHandler.java
  frontend/src/pages/login/Login.jsx
Labels: refactor
